
spring:
  datasource:
    url: jdbc:h2:mem:product_db
    driver-class-name: org.h2.Driver
    password:
    username: sa
  h2:
    console:
      path: /h2-console
  application:
    name: product-service
  jpa:
    show-sql: true
  cloud:
    discovery:
      enabled: true


server:
  port: 8082
